//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastrarUsuario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coppulaEntities : DbContext
    {
        public coppulaEntities()
            : base("name=coppulaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_administrador> tb_administrador { get; set; }
        public DbSet<tb_categoria> tb_categoria { get; set; }
        public DbSet<tb_cliente> tb_cliente { get; set; }
        public DbSet<tb_compra> tb_compra { get; set; }
        public DbSet<tb_endereco> tb_endereco { get; set; }
        public DbSet<tb_produto> tb_produto { get; set; }
    }
}
