//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastrarUsuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_administrador
    {
        public int id_administrador { get; set; }
        public string ds_email { get; set; }
        public string ds_login { get; set; }
        public string ds_senha { get; set; }
        public string ds_nivel_de_acesso { get; set; }
    }
}
