//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastrarUsuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_categoria
    {
        public int id_categoria { get; set; }
        public string nm_categoria { get; set; }
        public string ds_categoria { get; set; }
    }
}
