//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastrarUsuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compra
    {
        public int id_compra { get; set; }
        public System.DateTime dt_compra { get; set; }
        public Nullable<int> id_cliente { get; set; }
    }
}
